item{
	id: 1
	name: 'zero'
}
item{
	id: 1
	name: 'two'
}
item{
	id: 1
	name: 'three'
}
item{
	id: 1
	name: 'four'
}
item{
	id: 1
	name: 'circle'
}
item{
	id: 1
	name: 'heart'
}
item{
	id: 1
	name: 'star'
}
item{
	id: 1
	name: 'triangle'
}